from Example import DBType
from PyQt5 import QtCore, QtGui, QtWidgets

class ServicePacketBox:

    def __init__(self, packet, tabUI):
        self.packet = packet
        self.tabUI = tabUI
        self.servicePackGroup = None

    def createBox(self, parentWidget, parentLayout, index):
        self.servicePackGroup = QtWidgets.QGroupBox(parentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.servicePackGroup.sizePolicy().hasHeightForWidth())
        self.servicePackGroup.setSizePolicy(sizePolicy)
        self.servicePackGroup.setMinimumSize(QtCore.QSize(0, 91))
        self.servicePackGroup.setMaximumSize(QtCore.QSize(16777215, 91))
        self.servicePackGroup.setBaseSize(QtCore.QSize(0, 0))
        self.servicePackGroup.setStyleSheet("background-color: rgb(206, 255, 245);\n"
                                            "border-color: rgb(0, 170, 255);")
        self.servicePackGroup.setObjectName("servicePackGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.servicePackGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.hdLabel = QtWidgets.QLabel(self.servicePackGroup)
        self.hdLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.hdLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.hdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hdLabel.setObjectName("hdLabel")
        self.gridLayout.addWidget(self.hdLabel, 7, 6, 1, 1)
        self.cpuLabel = QtWidgets.QLabel(self.servicePackGroup)
        self.cpuLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.cpuLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cpuLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cpuLabel.setObjectName("cpuLabel")
        self.gridLayout.addWidget(self.cpuLabel, 7, 5, 1, 1)
        self.label_206 = QtWidgets.QLabel(self.servicePackGroup)
        self.label_206.setMinimumSize(QtCore.QSize(35, 25))
        self.label_206.setMaximumSize(QtCore.QSize(35, 25))
        self.label_206.setAutoFillBackground(False)
        self.label_206.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_206.setAlignment(QtCore.Qt.AlignCenter)
        self.label_206.setObjectName("label_206")
        self.gridLayout.addWidget(self.label_206, 6, 2, 1, 1)
        self.coreLabel = QtWidgets.QLabel(self.servicePackGroup)
        self.coreLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.coreLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.coreLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.coreLabel.setObjectName("coreLabel")
        self.gridLayout.addWidget(self.coreLabel, 7, 4, 1, 1)
        self.label_210 = QtWidgets.QLabel(self.servicePackGroup)
        self.label_210.setMinimumSize(QtCore.QSize(35, 25))
        self.label_210.setMaximumSize(QtCore.QSize(35, 25))
        self.label_210.setAutoFillBackground(False)
        self.label_210.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_210.setAlignment(QtCore.Qt.AlignCenter)
        self.label_210.setObjectName("label_210")
        self.gridLayout.addWidget(self.label_210, 6, 6, 1, 1)
        self.ramLabel = QtWidgets.QLabel(self.servicePackGroup)
        self.ramLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.ramLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ramLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ramLabel.setObjectName("ramLabel")
        self.gridLayout.addWidget(self.ramLabel, 7, 3, 1, 1)
        self.label_208 = QtWidgets.QLabel(self.servicePackGroup)
        self.label_208.setMinimumSize(QtCore.QSize(35, 25))
        self.label_208.setMaximumSize(QtCore.QSize(35, 25))
        self.label_208.setAutoFillBackground(False)
        self.label_208.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_208.setAlignment(QtCore.Qt.AlignCenter)
        self.label_208.setObjectName("label_208")
        self.gridLayout.addWidget(self.label_208, 6, 4, 1, 1)
        self.label_211 = QtWidgets.QLabel(self.servicePackGroup)
        self.label_211.setMinimumSize(QtCore.QSize(35, 25))
        self.label_211.setMaximumSize(QtCore.QSize(35, 25))
        self.label_211.setAutoFillBackground(False)
        self.label_211.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_211.setAlignment(QtCore.Qt.AlignCenter)
        self.label_211.setObjectName("label_211")
        self.gridLayout.addWidget(self.label_211, 6, 7, 1, 1)
        self.osLabel_17 = QtWidgets.QLabel(self.servicePackGroup)
        self.osLabel_17.setMinimumSize(QtCore.QSize(0, 30))
        self.osLabel_17.setMaximumSize(QtCore.QSize(16777215, 30))
        self.osLabel_17.setAlignment(QtCore.Qt.AlignCenter)
        self.osLabel_17.setObjectName("osLabel_17")
        self.gridLayout.addWidget(self.osLabel_17, 7, 2, 1, 1)
        self.label_207 = QtWidgets.QLabel(self.servicePackGroup)
        self.label_207.setMinimumSize(QtCore.QSize(35, 25))
        self.label_207.setMaximumSize(QtCore.QSize(35, 25))
        self.label_207.setAutoFillBackground(False)
        self.label_207.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_207.setAlignment(QtCore.Qt.AlignCenter)
        self.label_207.setObjectName("label_207")
        self.gridLayout.addWidget(self.label_207, 6, 3, 1, 1)
        self.bwLabel = QtWidgets.QLabel(self.servicePackGroup)
        self.bwLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.bwLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bwLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bwLabel.setObjectName("bwLabel")
        self.gridLayout.addWidget(self.bwLabel, 7, 7, 1, 1)
        self.startDateLabel = QtWidgets.QLabel(self.servicePackGroup)
        self.startDateLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.startDateLabel.setMaximumSize(QtCore.QSize(70, 30))
        self.startDateLabel.setStyleSheet("")
        self.startDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startDateLabel.setObjectName("startDateLabel")
        self.gridLayout.addWidget(self.startDateLabel, 7, 1, 1, 1)
        self.packEditButton = QtWidgets.QPushButton(self.servicePackGroup)
        self.packEditButton.setMinimumSize(QtCore.QSize(0, 25))
        self.packEditButton.setMaximumSize(QtCore.QSize(60, 30))
        self.packEditButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.packEditButton.setObjectName("packEditButton")
        self.gridLayout.addWidget(self.packEditButton, 6, 8, 1, 1)
        self.label_209 = QtWidgets.QLabel(self.servicePackGroup)
        self.label_209.setMinimumSize(QtCore.QSize(35, 25))
        self.label_209.setMaximumSize(QtCore.QSize(35, 25))
        self.label_209.setAutoFillBackground(False)
        self.label_209.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_209.setAlignment(QtCore.Qt.AlignCenter)
        self.label_209.setObjectName("label_209")
        self.gridLayout.addWidget(self.label_209, 6, 5, 1, 1)
        self.label_205 = QtWidgets.QLabel(self.servicePackGroup)
        self.label_205.setMinimumSize(QtCore.QSize(0, 30))
        self.label_205.setMaximumSize(QtCore.QSize(35, 30))
        self.label_205.setStyleSheet("")
        self.label_205.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_205.setObjectName("label_205")
        self.gridLayout.addWidget(self.label_205, 6, 0, 1, 1)
        self.endDateLabel = QtWidgets.QLabel(self.servicePackGroup)
        self.endDateLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.endDateLabel.setMaximumSize(QtCore.QSize(70, 30))
        self.endDateLabel.setStyleSheet("")
        self.endDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.endDateLabel.setObjectName("endDateLabel")
        self.gridLayout.addWidget(self.endDateLabel, 6, 1, 1, 1)
        self.packSnapshotButton = QtWidgets.QPushButton(self.servicePackGroup)
        self.packSnapshotButton.setMinimumSize(QtCore.QSize(0, 25))
        self.packSnapshotButton.setMaximumSize(QtCore.QSize(60, 30))
        self.packSnapshotButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.packSnapshotButton.setObjectName("packSnapshotButton")
        self.gridLayout.addWidget(self.packSnapshotButton, 6, 10, 1, 1)
        self.label_212 = QtWidgets.QLabel(self.servicePackGroup)
        self.label_212.setMinimumSize(QtCore.QSize(0, 30))
        self.label_212.setMaximumSize(QtCore.QSize(35, 30))
        self.label_212.setStyleSheet("")
        self.label_212.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_212.setObjectName("label_212")
        self.gridLayout.addWidget(self.label_212, 7, 0, 1, 1)
        self.packRemoveButton = QtWidgets.QPushButton(self.servicePackGroup)
        self.packRemoveButton.setMinimumSize(QtCore.QSize(0, 25))
        self.packRemoveButton.setMaximumSize(QtCore.QSize(60, 30))
        self.packRemoveButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.packRemoveButton.setObjectName("packRemoveButton")
        self.gridLayout.addWidget(self.packRemoveButton, 6, 9, 1, 1)
        parentLayout.addWidget(self.servicePackGroup, index, 0, 1, 1)
        self.servicePackGroup.setTitle("Service Pack " + str(index))

    def connectButtons(self):
        self.packEditButton.clicked.connect(self.editPacket)
        self.packRemoveButton.clicked.connect(self.removePacket)
        self.packSnapshotButton.clicked.connect(self.snapshot)

    def retranslateUI(self):
        _translate = QtCore.QCoreApplication.translate
        self.hdLabel.setText(_translate("UserWindow", str(self.packet.hd)))
        self.cpuLabel.setText(_translate("UserWindow", str(self.packet.cpu)))
        self.label_206.setText(_translate("UserWindow", "OS"))
        self.coreLabel.setText(_translate("UserWindow", str(self.packet.core)))
        self.label_210.setText(_translate("UserWindow", "HD"))
        self.ramLabel.setText(_translate("UserWindow", str(self.packet.ram)))
        self.label_208.setText(_translate("UserWindow", "Core"))
        self.label_211.setText(_translate("UserWindow", "BW"))
        self.osLabel_17.setText(_translate("UserWindow", str(self.packet.os)))
        self.label_207.setText(_translate("UserWindow", "RAM"))
        self.bwLabel.setText(_translate("UserWindow", str(self.packet.bw)))
        self.startDateLabel.setText(_translate("UserWindow", str(self.packet.createDate)))
        self.packEditButton.setText(_translate("UserWindow", "Edit"))
        self.label_209.setText(_translate("UserWindow", "CPU"))
        self.label_205.setText(_translate("UserWindow", "Start:"))
        self.endDateLabel.setText(_translate("UserWindow", str(self.packet.endDate)))
        self.packSnapshotButton.setText(_translate("UserWindow", "SnapShot"))
        self.label_212.setText(_translate("UserWindow", "End:"))
        self.packRemoveButton.setText(_translate("UserWindow", "Remove"))

    def editPacket(self):
        self.tabUI.editPacket(self.packet)

    def removePacket(self):
        self.tabUI.removePacket(self)
        self.servicePackGroup.setParent(None)

    def snapshot(self):
        #TODO store snapshot in a directory
        pass


